### ISSUE TITLE
SimpleTownsEconomy Error

### ISSUE THREAD

**Issue by xXMaTTHDXx** [JamesHealey94/SimpleTowns#19]
Using CraftBukkit version 1.7.9, alongside SimpleTowns and SimpleTownsExtras, I am not able to load up the plugin "SimpleTownsEconomy" upon starting my server. I have Vault installed, and the other two plugins seem to be operating correctly. 

Here is the error I'm getting in my console, when starting the server up: http://pastebin.com/tGUJrxZq

It seems as if there's an error in the plugin.yml

**Comment by JamesHealey94** [comment]
Seems to be a problem with SimpleTowns-Economy
https://github.com/MarkehMe/SimpleTowns-Economy/issues
