### ISSUE TITLE
Quick Suggestions

### ISSUE THREAD

**Issue by xXMaTTHDXx** [JamesHealey94/SimpleTowns#20]
I have a couple quick suggestions to balance out the features of creating towns.
- Only allow Leaders to claim chunks that are ATTACHED to the town they are in. Example: Don't allow people to claim a chunk, then walk to the other end of the map, and claim another chunk that's not attached to the town. 
- Allow regular Citizens to leave a town upon typing a command /town leave <townname>. Example: If a Leader decides to add a bunch of people to his town, Citizens can have the choice to leave.
- Add an option to accept/deny joining a town. Example: When Leader types /town add <playername>, the player will be greeted with a message, saying they have been invited to <townname> by <leader>. This will then give them two options, which they can accept and join the town, or deny and not be in the town.

I'm really enjoying the plugin so far, and I'd be more than happy if you could add a couple of these little features! Thanks.

**Comment by JamesHealey94** [comment]
Split up into 3 different issues. Hope you don't mind.
https://github.com/JamesHealey94/SimpleTowns/issues/22
https://github.com/JamesHealey94/SimpleTowns/issues/23
https://github.com/JamesHealey94/SimpleTowns/issues/21
